name: pdsim
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy<2  
  - scipy
  - matplotlib
  - pyyaml
  - h5py
  - xlsxwriter
  - wxpython
  - pandas
  - pip
  - pip:
    - CoolProp
    - Cython<3
    - quantities
